### PR TITLE
2.10

### PR DESCRIPTION
**Pull request by carlbarrdahl**
#44  

Any further changes needed for 2.10?  
https://developers.facebook.com/ads/blog/post/2017/07/18/marketing-api-2.10/
https://developers.facebook.com/docs/apps/changelog

### CODE REVIEW

**Comment by warling** [comment]
Back when I was first starting out with this SDK, I couldn't get things to work until I switched it to v2.10 (because I was developing a brand new Facebook app, and because it was new I couldn't use v2.9). I tried switching just the value you've changed to `v.210` in my `node_modules` code, but I still couldn't get it to run until I went through the entire codebase and did a search and replace. There were quite a few areas where `v2.9` showed up. Not just here, unfortunately.

**Comment by warling** [comment]
I suppose one other issue that should be considered are any API changes between v2.9 and v2.10; simply incrementing the version number may not be enough. I'm not (yet) all that familiar with either version of the API, but I suspect that v2.10 likely introduced other changes that probably need to be taken into consideration, like new (or removed) constants and parameters. It's probably worth investigating: https://developers.facebook.com/docs/apps/changelog

**Comment by warling** [comment]
Nothing to _my_ knowledge, but I've started working with this package (and the Marketing API itself) over the last couple of days.

**Comment by warling** [comment]
@carlbarrdahl, here's a more specific set of changes in v2.10; this is from https://developers.facebook.com/docs/apps/changelog. So, yes, there are a few other things that would need to be tidied up, like some of the constants in the `Insights` class.

v2 10

**Comment by lucascosta** [comment]
Thank you @carlbarrdahl . I have released a complete new version.

**Pull request closed without merging**
