### PR TITLE
AdImage fix

### PR DESCRIPTION
**Pull request by Stefflan00**
- Added AdImage to bundle file
- On AdImage.create() => fix to be able to return an AdImage Type

### CODE REVIEW

**Comment by Albinutte** [comment]
@Stefflan00 I used your code in my app to manage images, seems to be working fine 👍 Btw I also added `getImages` edge to `AdAccount`, would be nice to have it here too.

**Comment by Stefflan00** [comment]
@lucascosta is there any reason not to merge that pull ?

**Comment by lucascosta** [comment]
Sorry @Stefflan00 kind of missed this in the midst.

**Comment by lucascosta** [comment]
Just a note @Stefflan00 , `path.includes` is only Node 6 compatible, I'll be changing it to an `indexOf` comparison so it still works on Node 4.

**Pull request merged**
