### PR TITLE
Upgraded FB marketing API to 2.7

### PR DESCRIPTION
**Pull request by talha-asad**
There was no change needed in any of the objects.

I upgraded version numbers, and devDependencies, dependencies, standard version and bower component versions. 

Had to change 2 function names, due to StandardJS enforcing camel-case starting from version 7.

All tests are passing.

### CODE REVIEW

**Comment by talha-asad** [comment]
Had to change 2 function names, due to StandardJS enforcing camel-case starting from version 7.

**Comment by lucascosta** [comment]
Awesome work. I didn't see the need for your last commit though, putting `requests` as a dependency. I was able to run the integrations tests with your code without it, can you double check please?

**Comment by talha-asad** [comment]
Yup you're right, I think I added it cause NPM said something about unmet dependency.

**Comment by lucascosta** [comment]
Would like to reset these last commits and `push --force` without them to make your PR slimmer?

**Comment by talha-asad** [comment]
Sure

**Comment by talha-asad** [comment]
I added AdImage, seems you had that one missing.

**Comment by talha-asad** [comment]
#5 submitted, single commit PR.

**Pull request closed without merging**
